# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d82c233c51103758d2539bed707733dc1d6e83bb54143c6932582243fcd1426fa80fc6ebbbe5da6a40172f85f40a8532f4e0d9e157f1b72dcc1dba19b1ca75

test:
  secret_key_base: c296df869ff968c4624e0fc682697f22119e04d078aaf846790b601c29ae3f3d89f61db1e07617805e1854490fc0aa2f4e333fa8ae05ce87ef267778703fd277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
